// Game Configuration
const CONFIG = {
  GRID_SIZE: 20,
  CELL_SIZE: 30,
  GAME_SPEEDS: [0.5, 1, 2, 5],
  STARTING_BUDGET: 10000,
  STARTING_DAY: 1,
  STARTING_TIME: 480, // 8:00 AM in minutes
  WALL_COST: 50,
  DOOR_COST: 25,
  CELL_COST: 150,
  CANTEEN_COST: 200,
  YARD_COST: 250,
  SOLITARY_CELL_COST: 100,
  KITCHEN_COST: 300,
  INFIRMARY_COST: 400,
  WORKSHOP_COST: 350,
  // Financial Configuration
  INMATE_DAILY_STIPEND: 150,
  GUARD_DAILY_SALARY: 180,
  INMATE_DAILY_FOOD_COST: 20,
  FACILITY_DAILY_UTILITY_BASE: 50,
  STRUCTURE_DAILY_UTILITY: 2,
  STRUCTURE_DAILY_MAINTENANCE: 1,
  COMMISSARY_REVENUE_PER_INMATE: 15,
  PHONE_REVENUE_PER_INMATE: 5,
  WORKSHOP_DAILY_REVENUE: 50,
  DAILY_ADMIN_COST: 40,
  LOW_FUNDS_THRESHOLD: 1000,
  EMERGENCY_GRANT_AMOUNT: 2500
};

// Export for use in other files
export { CONFIG };
if (typeof window !== 'undefined') {
  window.CONFIG = CONFIG;
}